### ISSUE TITLE
Error reading TEXT configuration file with 1.0.7

### ISSUE THREAD

**Issue by shivajibr** [xframium/xframium-java#60]
Release 1.0.7 throws Null pointer exception when reading the text configuration file

Jan 03, 2017 6:40:29 PM org.xframium.driver.TXTConfigurationReader readFile
SEVERE: Error reading configruation file
java.lang.NullPointerException
	at org.xframium.driver.TXTConfigurationReader.readFile(TXTConfigurationReader.java:106)
	at org.xframium.driver.TXTConfigurationReader.readFile(TXTConfigurationReader.java:88)
	at org.xframium.driver.AbstractConfigurationReader.readConfiguration(AbstractConfigurationReader.java:137)
	at org.xframium.driver.AbstractConfigurationReader.readConfiguration(AbstractConfigurationReader.java:111)
	at com.allState.testDriver.TestDriver.main(TestDriver.java:28)

**Problem:**
In TXTConfigurationReader, configProperties is not getting initialized.

On line # 80, private Map<String,String> configProperties;

should be

private Map<String,String> configProperties = new HashMap<String,String>( 10 ); **(Same as XMLConfigurationReader)**

**Comment by allengeary** [comment]
Resolved in 1.0.8
